[project]
name = "comfyui_prompt_manager"
description = "Prompt manager, prompt crafter, visual prompt"
readme = "README.md"
version = "2.2.0"
license = { file = "LICENSE.txt" }
dependencies = []

[project.urls]
Repository = "https://github.com/Fictiverse/ComfyUI_Prompt_Manager"

[tool.comfy]
PublisherId = "fictiverse"
DisplayName = "🗂️ Prompt Manager"
